=pod

=encoding UTF-8

=head1 NAME

AnyEvent::ProcessPool - A multi-process pool for Perl

=head1 VERSION

version 0.01

=head1 SYNOPSIS

  use AnyEvent::ProcessPool;

  my $pool = AnyEvent::ProcessPool->new(
    workers  => 8,
    max_reqs => 10,
  );

  my $async = $pool->run(sub{
    # do stuff...
  });

  my $result = $async->();

=head1 DESCRIPTION

Executes code using a pool a forked Perl subprocesses. Supports configurable
pool size, automatically restarting processes after a configurable number of
requests, and closures (with the caveat that changes are not propagated back to
the parent process).

=head1 METHODS

=head2 new

=head2 run

=head1 DIAGNOSTICS

=head1 SEE ALSO

=over

=item L<Parallel::ForkManager>

=back

=head1 AUTHOR

Jeff Ober <sysread@fastmail.fm>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2017 by Jeff Ober.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
